version: "3.7"
services:
  frontend:
    restart: always
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: vault-frontend
    env_file:
      - "./fe/.env"
    depends_on: 
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./fe:/app

  dapp:
    restart: always
    build:
      context: ./dapp-demo
      dockerfile: Dockerfile
    container_name: vault-dapp-demo
    env_file:
      - "./dapp-demo/.env"
    depends_on:
      - frontend
      - backend
    ports:
      - "3030:3030"
    volumes:
      - ./dapp-demo:/app

  backend:
    restart: always
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        GITLAB_TOKEN: ${GITLAB_TOKEN}
        GITLAB_USER: ${GITLAB_USER}
    container_name: vault-backend
    env_file:
      - "./api/.env"
    depends_on: 
      - redis
      - postgres
    ports:
      - "3010:3000"
    volumes:
      - ./api:/app
  
  redis:
    image: "redis:alpine"
    restart: always
    container_name: vault-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:alpine
    restart: always
    container_name: vault-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes: 
      - postgres-data:/var/lib/postgresql/data
volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
    