version: '3.8'
services:
  wallet:
    build:
      context: ./wallet-checkout-demo
    container_name: wallet-app
    ports:
      - "3000:3000"
    env_file:
      - ./wallet-checkout-demo/.env
    volumes:
      - ./wallet-checkout-demo:/app
      - /app/node_modules
    stdin_open: true
    tty: true

  merchant:
    build:
      context: ./merchant-checkout-demo
    container_name: merchant-app
    ports:
      - "3001:3000"
    env_file:
      - ./merchant-checkout-demo/.env
    volumes:
      - ./merchant-checkout-demo:/app
      - /app/node_modules
    stdin_open: true
    tty: true
