version: "3.7"
# NOTE: Changeme
services:
  frontend:
    restart: always
    build:
      context: ./fe
      dockerfile: Dockerfile
    container_name: vault-frontend
    env_file:
      - "./fe/.env"
    depends_on: 
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./fe:/app
